In [3]:
import numpy as np

# Load iris dataset (only 4 numerical columns)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# 1. Define A and B, stack vertically and horizontally
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

v_stack = np.vstack((A, B))
h_stack = np.hstack((A, B))

print("Vertical Stack:\n", v_stack)
print("Horizontal Stack:\n", h_stack)

# 2. Find common elements
A_flat = A.flatten()
B_flat = B.flatten()
common_elements = np.intersect1d(A_flat, B_flat)
print("Common Elements:\n", common_elements)

# 3. Extract elements in range (e.g., 5 to 10) from A
elements_in_range = A[(A >= 2) & (A <= 3)]
print("Elements in range [2, 3]:\n", elements_in_range)

# 4. Filter rows from iris_2d where petal length > 1.5 and sepal length < 5.0
filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered Iris Rows:\n", filtered_rows)


Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
Common Elements:
 []
Elements in range [2, 3]:
 [2 3]
Filtered Iris Rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [4]:
import pandas as pd
import numpy as np

# 1. Filter 'Manufacturer', 'Model', and 'Type' for every 20th row starting from 0
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print("Every 20th row:\n", filtered_df)

# 2. Replace missing values in Min.Price and Max.Price columns with their mean
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)
print("Missing values filled for Min.Price and Max.Price.")

# 3. Get rows where row sum > 100
df2 = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4), columns=['A', 'B', 'C', 'D'])
rows_gt_100 = df2[df2.sum(axis=1) > 100]
print("Rows with row sum > 100:\n", rows_gt_100)


Every 20th row:
    Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small
Missing values filled for Min.Price and Max.Price.
Rows with row sum > 100:
      A   B   C   D
1   30  34  34  37
3   36  31  10  37
4   26  37  37  22
6   29  29  36  21
7   33  28  39  20
9   23  25  28  25
11  29  32  36  11
12  37  30  38  36


<ipython-input-4-40e1d642326e>:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
<ipython-input-4-40e1d642326e>:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True